grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: LoadBalancer
  dashboards:
    default:
      pulsar-dashboard:
        json: |
          {
            "title": "Pulsar Monitoring",
            "panels": [
              {
                "title": "Broker Throughput",
                "type": "graph",
                "targets": [{"expr": "pulsar_broker_throughput"}]
              },
              {
                "title": "Topic Backlog",
                "type": "graph",
                "targets": [{"expr": "pulsar_topic_backlog"}]
              }
            ]
          }

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        app: pulsar-broker